spring.application.name=real-estate-backend
spring.datasource.url=jdbc:mysql://localhost:3306/real_eastate_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=secretkey123
jwt.expiration=86400000
cloudinary.cloud-name=drhjhrsxi
cloudinary.api-key=195725628726872
cloudinary.api-secret=GMAtYukm3Mgs0ZaPb0vg-mgUZ3M

server.port=8080